"""Indexing

Revision ID: 95380cad14fb
Revises: 4643bf9d016e
Create Date: 2021-10-06 23:58:27.576140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95380cad14fb'
down_revision = '4643bf9d016e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_index(op.f('ix_reply_id'), 'reply', ['id'], unique=False)
    op.drop_index('ix_user_image_file', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_user_image_file', 'user', ['image_file'], unique=False)
    op.drop_index(op.f('ix_reply_id'), table_name='reply')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    # ### end Alembic commands ###
